# Generated by Django 5.1.3 on 2024-11-19 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_client_alter_reservation_rental_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_basket',
            name='Client',
        ),
        migrations.AddField(
            model_name='client',
            name='shopping_basket',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.shopping_basket'),
            preserve_default=False,
        ),
    ]
