# Generated by Django 5.1.3 on 2024-11-17 09:46

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_reservation_rental_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rental_end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 11, 17))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rental_start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 11, 17))]),
        ),
        migrations.AlterField(
            model_name='shopping_basket',
            name='rental_end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 11, 17))]),
        ),
        migrations.AlterField(
            model_name='shopping_basket',
            name='rental_start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 11, 17))]),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_validated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
