# Generated by Django 5.1.3 on 2024-11-18 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_reservation_rental_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_basket',
            name='Client',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.client'),
            preserve_default=False,
        ),
    ]
