# Generated by Django 5.1.3 on 2024-11-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_reservation_rental_end_date_and_more'),
        ('business', '0007_alter_reservation_rental_end_date_and_more'),
    ]

    operations = [
    ]
