# Generated by Django 5.1.3 on 2024-11-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_port_ubication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ships/'),
        ),
    ]
