# Generated by Django 5.1.3 on 2024-11-19 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('business', '0002_client_alter_reservation_rental_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.client'),
        ),
    ]
