# Generated by Django 5.1.3 on 2024-11-17 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Apellidos',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default='merengue', max_length=100, validators=[django.core.validators.MinLengthValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.CharField(default='test@mail.com', max_length=50, validators=[django.core.validators.MinLengthValidator(0)]),
            preserve_default=False,
        ),
    ]
