# Generated by Django 5.1.3 on 2024-11-19 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_nombre_customuser_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.CharField(default=1, max_length=50, validators=[django.core.validators.MinLengthValidator(0)]),
            preserve_default=False,
        ),
    ]
